apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  namespace: edygc1988-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: ms-payments
          image: edygc1988/ms_payments:{{imageTag}}
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "1"
              memory: "250Mi"
          startupProbe:
            httpGet:
            path: /startup
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: microservicio
            - secretRef:
                name: microservicio-secret
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio
  namespace: edygc1988-dev
spec:
  type: LoadBalancer
  selector:
    app: microservicio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservicio
  namespace: edygc1988-dev
data:
  LOG_LEVEL: "DEBUG"
---
apiVersion: v1
kind: Secret
metadata:
  name: microservicio-secret
  namespace: edygc1988-dev
type: Opaque
stringData:
  DB_PASSWORD: "contraseña-segura"
  API_KEY: "api-key-segura"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservicio
  namespace: edygc1988-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservicio
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
