{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db-password: {{ .Values.database.password | quote }}
  api-password: {{ .Values.api.password | quote }}
{{- end }}
